dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    directories:
        - $HOME/download/
        - $HOME/miniconda3/

before_install:
  - bash .travis/travis_before_install.sh


install:
  - export PATH="/home/travis/miniconda3/bin:$PATH"
  - echo $PATH
  - bash src/install/conda_env.sh
  - source activate smsk_tuxedo2
  - Rscript src/install/install_r_packages.R

script:
  - export PATH="/home/travis/miniconda3/bin:$PATH"
  - echo $PATH
  - source activate smsk
  - snakemake -j
