# Travis' configuration file
---
dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    directories:
        - $HOME/download/
        - $HOME/miniconda3/

before_install:
    - bash .travis/travis_before_install.sh


install:
    - export PATH="/home/travis/miniconda3/bin:$PATH"
    - echo $PATH
    - conda install --yes -c bioconda snakemake=5.0

script:
    - export PATH="/home/travis/miniconda3/bin:$PATH"
    - echo $PATH
    - snakemake --use-conda -j
